var text = [
    'Ut vel diam eget ante tincidunt dapibus eu eu purus. Quisque mattis neque ut gravida lacinia.',
    'Donec sit amet imperdiet lorem. Duis urna libero, pellentesque non metus eget, consequat luctus leo.',
    'Sed blandit nulla id risus aliquet interdum. Quisque ornare orci vitae tincidunt molestie.',
    'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Integer finibus elementum tellus a aliquam.',
    'Quisque fermentum orci tellus, vitae blandit ipsum varius eu. Nunc nec metus sit amet nulla condimentum rutrum non quis orci.',
    'In hac habitasse platea dictumst. Nunc tincidunt aliquet tortor, scelerisque varius orci consequat vitae.',
    'Integer ac augue turpis. Sed finibus dolor vitae tempor tincidunt. Donec commodo, mi quis maximus sodales, ligula augue vehicula libero, eget convallis purus velit non quam.',
    'Sed sollicitudin gravida felis. Vestibulum velit erat, molestie ut feugiat in, laoreet eget ligula.',
    'Donec a erat feugiat, lacinia sapien vitae, consequat eros. Vivamus placerat quam at facilisis venenatis.',
    'Proin libero ipsum, vehicula eu nibh id, mollis pulvinar nulla. Praesent pellentesque aliquet pharetra.',
    'Nunc euismod, sapien vitae sodales malesuada, turpis metus lacinia ante, non viverra tortor justo eget sem.',
    'Aliquam eleifend condimentum lectus ut lacinia. Ut tempor dolor sed tellus congue mattis.',
    'Phasellus est dolor, convallis luctus auctor vel, consectetur eget lectus. Nulla vehicula quis sem in cursus.',
    'Nulla porta felis bibendum mattis rutrum. Maecenas sit amet pellentesque lorem. Sed id dui diam. Duis eget arcu tortor.',
    'Integer scelerisque ultricies dolor quis facilisis. Maecenas tincidunt sapien at purus maximus, at luctus orci dignissim.',
    'Phasellus non tortor ut enim eleifend vestibulum. Proin maximus, nisi id placerat semper, mi nulla porttitor ipsum, nec commodo libero enim non mi.',
    'Phasellus eget odio tortor. Aenean rhoncus sodales tellus ut vulputate. Aenean tempor velit non arcu molestie porta.',
    'Proin tristique massa sed tincidunt sodales. Ut nec urna non magna elementum dictum mollis eget nulla.',
    'Donec efficitur pretium felis pulvinar semper. Aliquam at mauris vitae augue rhoncus efficitur.',
    'Morbi eros odio, accumsan sit amet lobortis in, euismod eu ante. Cras placerat sit amet felis et fringilla.',
    'Pellentesque placerat ex magna, et malesuada purus euismod nec. Pellentesque faucibus sagittis tortor, ac maximus arcu malesuada ac.',
    'Nullam vehicula lectus enim, ac gravida mauris viverra in. Morbi interdum egestas euismod.',
    'Aenean dignissim consequat lacus quis ultrices. In tincidunt urna ac dolor gravida, a vehicula ante posuere.',
    'Integer eu felis id mi porttitor volutpat ac nec nisl. Ut sit amet ex eget leo tristique laoreet.',
    'Pellentesque quis lacus risus. Nullam eu ex eget ligula rhoncus imperdiet. Proin blandit iaculis consectetur.',
    'Nulla facilisi. Interdum et malesuada fames ac ante ipsum primis in faucibus.',
    'Duis vehicula erat quis tellus porttitor accumsan. Sed in iaculis sem, eget blandit urna. Suspendisse potenti.',
    'Nullam tempus nisi cursus facilisis volutpat. Aliquam imperdiet diam eu enim pretium accumsan.',
    'Maecenas tincidunt aliquam tellus nec lacinia. Vestibulum porttitor commodo magna, pretium semper turpis viverra non.',
    'Duis vitae dictum sapien, eu pharetra purus. Aenean volutpat orci nisl, ac pharetra dolor sagittis porttitor.',
    'Morbi quam nibh, elementum eget tempus hendrerit, iaculis non neque. Nam congue tellus non dui pulvinar tempor.',
    'Integer euismod ultrices lacinia. Integer rutrum blandit nisl, non fermentum ante hendrerit non. Nulla ac egestas erat.'
];